
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/componets/SideNav";
import Header from "@/componets/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Referral Creadit System App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden bg-amber-700 `}
      >
        {/* Sidebar */}
        <SideNav />

        {/* Main content area */}
        <div className="flex flex-col flex-1 overflow-hidden">
           {/* Header content */}
          <Header />
          {/* Scrollable content */}
          <main className="flex-1 overflow-y-auto bg-white p-2 no-scrollbar">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
